### ISSUE TITLE
Can the library be used for USB MIDI ?

### ISSUE THREAD

**Issue by Albertloo** [FortySevenEffects/arduino_midi_library#99]
New to Arduino (with experience in Java), I'm trying to read MIDI In from 5-pin MIDI port and send the MIDI message to MIDI out via USB (for the Arduino Uno R3, also read flashing the Arduino 8u2 chip with Midi firmware).

Main goal of the project is to convert program change message from a foot controller with 5-pin Midi Output port to an effect unit (Zoom G3) with only a USB port.

Thanks!

**Comment by franky47** [comment]
Yes, since the 8u2 chip would handle USB MIDI stuff, you'd need to create a bridge between a serial MIDI input (connected to your DIN port) and separate serial MIDI output (connected to the TX line that feeds the 8u2).
Check out the DualMerger example to see how to do that, although in your case I'd recommend using a ProgramChange callback that emits messages onto the 8u2 interface:
https://github.com/FortySevenEffects/arduino_midi_library/blob/master/examples/DualMerger/DualMerger.ino
